apiVersion: v1
kind: PersistentVolume
metadata:
  name: runner-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/runner
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: runner-pvc
  namespace: jenkins-runner
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi