apiVersion: v1
kind: Service
metadata:
  name: jenkins-runner
  namespace: jenkins-runner
spec:
  type: NodePort
  ports:
    - port: 22
      targetPort: 22
      nodePort: 32222
  selector:
    app: jenkins-runner