apiVersion: v1
kind: Pod
metadata:
  name: cpu-hog
  namespace: monitoring
spec:
  containers:
    - name: cpu-hog
      image: busybox
      command: ["sh", "-c", "while true; do :; done"]
      resources:
        limits:
          cpu: "2"  # Limite le CPU à 2 cores
