apiVersion: v1
kind: Pod
metadata:
  name: failed-pod
  namespace: monitoring
spec:
  restartPolicy: Never
  containers:
    - name: failed-container
      image: busybox
      command: ["sh", "-c", "exit 1"]
