apiVersion: v1
kind: Service
metadata:
  name: api-bcff
  namespace: prod
  labels:
    app: api-bcff
spec:
  type: NodePort
  selector:
    app: api-bcff
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080